### ISSUE TITLE
window.fetch

### ISSUE THREAD

**Issue by tyoshino** [slightlyoff/ServiceWorker#581]
List of issues blocking expose of `window.fetch`
- [x] #535 `[Replaceable]`
    - Resolved
- [ ] Request
    - [x] `RequestInit.method`: No change required
    - [ ] `RequestInit.headers`
         - Keep `charset` magic? https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-66414845
    - [ ] Restrict acceptable values for `RequestInit.mode`?
        - `"same-origin"` and `"cors"` are safe
        - `"no-cors"` is meaningful when
            - For populating objects from Request object https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-66267847
            - window.cache is available https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-66501027
        - `CORS-with-forced-preflight` doesn't make sense for the Fetch API. Just omit it. See https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-66267847
    - [x] Any unsafe value for `RequestInit.credentials`? => No https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-66413001
    - [ ] `RequestInit.cache` limit to same-origin? (not only-window issue) #585
- [ ] Response
    - [ ] `type`: Safe?
        - [ ] Can be abused for port scanning? https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-70056571
            - fine once private addresses are blocked as mixed content? https://github.com/slightlyoff/ServiceWorker/issues/581#issuecomment-70057322
    - [x] `url`: No change required
    - [x] `status`: No change required
    - [x] `statusText`: No change required
    - [x] `headers`

----

I'd like to start a tracking issue to sort out issues need to be resolved to expose `fetch()` on `window`.

Regarding RequestInit.mode, I guess we can accept `"same-origin"` and `"cors"`. Right? Reading the history of forced-preflight (http://dev.w3.org/cvsweb/2006/webapi/XMLHttpRequest-2/Overview.src.html#rev1.40), I guess that we don't need any option to choose with-forced-preflight.

It seems `mode` == `no CORS` is not meaningful in window. Should we allow this? With opaque filtering, it should be safe even if we accept it?

**Comment by tyoshino** [comment]
Hmm, it seems that by using `RequestInit.mode=="no-cors"` and looking at the `type` on the returned `Response`, we can determine whether a certain host exists && is_serving_HTTP. Shouldn't this be considered as a way for port scanning?

Make a cross-origin request using `fetch()` from origin X to Y.
- If Y points at a working web server, the result would be "opaque"
- If not, the result would be "error". I.e. the Promise would be rejected

Cf. the WebSocket API not returning details of opening handshake. See the big red warning in https://html.spec.whatwg.org/multipage/comms.html#feedback-from-the-protocol

/cc @horo-t

**Comment by tyoshino** [comment]
`Response.headers` is ok. Same as XHR, they're filtered.

The step checking simpleness of the given method and the special guard `request-no-CORS` prevent non-simple requests from being issued using `RequestInit.mode=="no-cors"`. So, this is ok.

Now I've done reviewing all the attributes. It seems we need to take care of `RequestInit.cache` and `Response.type`, but except for them, it seems we're ready to expose Fetch API to window and (shared)worker.

**Comment by annevk** [comment]
@tyoshino from what I remember @jakearchibald wanted to expose `type` so we would know whether it was worth caching the response.

I believe that @mikewest and also @sicking have plans to eventually make local IP addresses Mixed Content, but until that happens this seems pretty hairy, yes 😟

However, it's also unclear how we could make opaque responses work without this. Can some other API such as `<iframe>` not already be abused?

**Comment by jakearchibald** [comment]
`<iframe>` can be abused in Firefox, which doesn't fire a load event for hosts that don't resolve. Chrome still fires a load event. Test: https://jsbin.com/nuvaso/edit

`<img>` can be used fairly reliably due to `/favicon.ico` https://jsbin.com/sumuji/1/edit?html,js,output

Appcache can be used, by setting the external URL as an explicit cache entry and seeing if the cache succeeds.

**Comment by tyoshino** [comment]
> worth caching

I see.

> Mixed Content

OK. I don't come up with any mitigation for now. We plan to disallow `Request.mode == 'no-cors'` in window for the initial release and wait for solutions.

**Comment by annevk** [comment]
@tyoshino if you only disable it in window you are not solving anything. Just making the attack slightly harder.

**Comment by tyoshino** [comment]
@annevk Right...

We're discussing this a little with our security team. As you said, @mikewest et. al are working on local/intra IP detection (http://crbug.com/378566). But it seems we're not so close to finish the work.

So, to address the issue temporarily, I think we have two options for window:

- a) Disallow construction of a Request with RequestInit.mode == no-cors
- b) Make fetch() fulfill the returned Promise even for network error && disable Response.type attribute

Only (b) works for SW. We need to dispatch no-cors requests coming from the page. It's critical.

**Comment by annevk** [comment]
(b) seems hardly acceptable. You might end up caching a whole bunch of network errors without a way to find out.

**Comment by tyoshino** [comment]
@annevk Right. This is just a bandaid proposal I could come up with to address the issue for short-term.

**Comment by jakearchibald** [comment]
Did you see my comment about hosts already being detectable using
iframe/img? Appcache even let's you tell 404s from 200s, but I guess that
was a mistake.

**Comment by tyoshino** [comment]
@jakearchibald I've forwarded your post to the security team when I contacted them. I'll CC you.

**Comment by jakearchibald** [comment]
It shipped!
